---
# ansible hosts
all:
  hosts: #全部入りのサーバー
    163.43.131.53:
      server_id: s1
  children:
    app: #appのサーバー
      hosts: 
        163.43.208.174:
          server_id: s2
    db: #DBのサーバー
      hosts: 
        163.43.185.85：　
          server_id: s3
    proxy: #nginxのサーバー
      hosts:
        163.43.208.174:
          server_id: s2
        
